name: CI - Windows

on:
  workflow_call:
    inputs:
      amdgpu_families:
        type: string
      artifact_run_id:
        type: string
      test_runs_on:
        type: string
      windows_use_prebuilt_artifacts:
        type: string
      extra_cmake_options:
        type: string
        default: "-DBUILD_TESTING=ON"

permissions:
  contents: read

jobs:
  build_windows_packages:
    name: Build
    if: ${{ inputs.windows_use_prebuilt_artifacts == 'false' }}
    uses: ./.github/workflows/build_windows_packages.yml
    with:
      amdgpu_families: ${{ inputs.amdgpu_families }}
      extra_cmake_options: ${{ inputs.extra_cmake_options }}
    permissions:
      contents: read
      id-token: write

  test_windows_packages:
    needs: [build_windows_packages]
    name: Test
    # If the dependent job failed/cancelled, this job will not be run
    # The windows_use_prebuilt_artifacts "or" statement ensures that tests will run if previous build step is run or skipped.concurrency.
    if: >-
      ${{
        !failure() &&
        !cancelled() &&
        (
          inputs.windows_use_prebuilt_artifacts == 'false' ||
          inputs.windows_use_prebuilt_artifacts == 'true'
        )
      }}
    strategy:
      fail-fast: false
    uses: ./.github/workflows/test_packages.yml
    with:
      amdgpu_families: ${{ inputs.amdgpu_families }}
      test_runs_on: ${{ inputs.test_runs_on }}
      artifact_run_id: ${{ inputs.artifact_run_id }}
      platform: "windows"
