name: Release Windows PyTorch Wheels

on:
  workflow_call:
    inputs:
      amdgpu_family:
        required: true
        type: string
      release_type:
        description: The type of release to build ("nightly", or "dev")
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      s3_staging_subdir:
        description: Staging subdirectory to push the wheels for test
        type: string
        default: "v2-staging"
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        type: string
        default: "https://d25kgig7rdsyks.cloudfront.net/v2"
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        required: true
        type: string
      rocm_version:
        description: ROCm version to pip install
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the reference or SHA that triggered the workflow."
        type: string
  workflow_dispatch:
    inputs:
      amdgpu_family:
        type: choice
        options:
          - gfx110X-dgpu
          - gfx1151
          - gfx120X-all
          - gfx94X-dcgpu
          - gfx950-dcgpu
        default: gfx1151
      release_type:
        description: The type of release to build ("nightly", or "dev")
        type: string
        default: "dev"
      s3_subdir:
        description: S3 subdirectory, not including the GPU-family
        type: string
        default: "v2"
      s3_staging_subdir:
        description: "Staging subdirectory to push the wheels for test"
        type: string
        default: "v2-staging"
      cloudfront_url:
        description: CloudFront URL pointing to Python index
        type: string
        default: "https://d25kgig7rdsyks.cloudfront.net/v2"
      cloudfront_staging_url:
        description: CloudFront base URL pointing to staging Python index
        type: string
        default: "https://d25kgig7rdsyks.cloudfront.net/v2-staging"
      rocm_version:
        description: ROCm version to pip install
        type: string
      ref:
        description: "Branch, tag or SHA to checkout. Defaults to the reference or SHA that triggered the workflow."
        type: string
        default: ''


permissions:
  id-token: write
  contents: read

jobs:
  release:
    name: Release | ${{ inputs.amdgpu_family }} | py ${{ matrix.python_version }}
    strategy:
      fail-fast: false
      matrix:
        # python_version: ["3.11", "3.12", "3.13"]
        python_version: ["3.12"]  # DO NOT SUBMIT - limited for testing
        pytorch_version: ["release/2.8", "release/2.9", "main"]
        include:
          - pytorch_version: release/2.8
            pytorch_patchset: rocm_2.8
          - pytorch_version: release/2.9
            pytorch_patchset: rocm_2.9
          - pytorch_version: main
            pytorch_patchset: main

    uses: ./.github/workflows/build_windows_pytorch_wheels.yml
    with:
      amdgpu_family: ${{ inputs.amdgpu_family }}
      python_version: ${{ matrix.python_version }}
      release_type: ${{ inputs.release_type }}
      s3_subdir: ${{ inputs.s3_subdir }}
      s3_staging_subdir: ${{ inputs.s3_staging_subdir }}
      cloudfront_url: ${{ inputs.cloudfront_url }}
      cloudfront_staging_url: ${{ inputs.cloudfront_staging_url }}
      rocm_version: ${{ inputs.rocm_version }}
      pytorch_version: ${{ matrix.pytorch_version }}
      pytorch_patchset: ${{ matrix.pytorch_patchset }}
      ref: ${{ inputs.ref || '' }}
